/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QHWGqkrgi2Z
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
// import { Le } from "@/components/recording_button"
import { LectureButton } from "@/components/recording_button"
import { TalkButton } from "@/components/talkbutton"
import { GearIcon } from "@radix-ui/react-icons"
import { AudioRecorder } from "@/components/audio-recorder"

export default async function Dashboard() {
  return (
    <div className="min-h-screen bg-white py-5">
      <div className="container mx-auto px-4 ">
        <div className="flex gap-10 mt-8">
          <aside className="w-64">
            <div className="p-7 bg-white p-4 rounded-lg">
              <h2 className="font-semibold text-gray-800 text-xl mb-7">Courses</h2>
              <nav className="flex flex-col gap-4">
                <Button className="justify-start text-green-600 font-medium text-lg p-4" variant="secondary">
                  Maths 2023
                </Button>
                <Button className="justify-start font-medium text-lg p-4"  variant="ghost">
                  Physics 2023
                </Button>
              </nav>
            </div>
          </aside>
          <main className="flex-1">
            <header className="p-4 flex justify-between items-center py-4">
            <h1 className="text-3xl font-bold text-gray-800">Course Overview</h1>
              <div className="flex space-x-4">
                  <Button className="flex items-center space-x-2" variant="secondary"><InfoIcon className="text-gray-700 w-5 mr-2"/>Course Information</Button>
                  <Button className="flex items-center space-x-2" variant="secondary"><BarChartIcon className="text-gray-700 w-5 mr-2" />Student Performance</Button>
                  <Button className="flex items-center space-x-2" variant="secondary"><MessageCircleIcon className="text-white-700 w-5 mr-2" />Chat</Button>
                  <Button className="flex items-center space-x-2" variant="secondary"><GearIcon className="text-white-700 w-5 mr-2" />Settings</Button>
              </div>
            </header>
            <div className="bg-white p-4 rounded-lg ">
              {/* <Button className="bg-green-500 text-white px-4 py-2 rounded-md flex items-center space-x-2">
                <PlusIcon className="text-white" />
                <span>Add new lecture</span>
              </Button> */}
              {/* <AudioRecoderButton></AudioRecoderButton> */}
              <LectureButton></LectureButton>
              {/* <TalkButton></TalkButton> */}
              <div className="mt-6">
                <div className="flex items-center justify-between p-6 rounded-lg bg-gray-50 mb-7">
                  <div>
                    <h3 className="text-lg font-semibold mb-3">April 2nd</h3>
                    <p className="text-gray-600">Vectors, Norms, Cross-Product</p>
                  </div>
                  <ChevronRightIcon className="text-gray-400" />
                </div>
                <div className="flex items-center justify-between p-6 rounded-lg bg-gray-50">
                  <div>
                    <h3 className="text-lg font-semibold mb-3">March 3rd</h3>
                    <p className="text-gray-600">Matrix Calculations, Vector Spaces</p>
                  </div>
                  <ChevronRightIcon className="text-gray-400" />
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    </div>
  )
}

function AddNewLecture() {
  return
  // TODO implement this behaviour
}

function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}


function MessageCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 21 1.9-5.7a8.5 8.5 0 1 1 3.8 3.8z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
